# docker build -t jukebox_alexa_python .
# docker run --rm -it -v $HOME/.aws:/root/.aws -v ${PWD}:/project jukebox_alexa_python /bin/bash
# docker run --rm -it -v $HOME/.aws:/root/.aws -v ${PWD}:/project jukebox_alexa_python songlist_upload
# docker run --rm -it -v $HOME/.aws:/root/.aws -v ${PWD}:/project jukebox_alexa_python songlist_index

FROM python:3.6

RUN mkdir /project
WORKDIR /project

RUN pip install awscli
