version: 0.2
phases:
  build:
    commands:
      - cd JukeboxAlexa
      - dotnet restore
      - dotnet publish
      - cd bin/Debug/netcoreapp2.0/publish
      - zip -r jukeboxAlexa.zip .
      - ls -la .
artifacts:
  files: bin/Debug/netcoreapp2.0/publish/jukeboxAlexa.zip
