# docker build -t jukebox_alexa_python .
# docker run --rm -it -v $HOME/.aws:/root/.aws -v ${PWD}:/project jukebox_alexa_python /bin/bash
# docker run --rm -it -v $HOME/.aws:/root/.aws -v ${PWD}:/project jukebox_alexa_python songlist_upload
# docker run --rm -it -v $HOME/.aws:/root/.aws -v ${PWD}:/project jukebox_alexa_python songlist_index

FROM python:3.6

RUN mkdir /project
WORKDIR /project

RUN pip install awscli

COPY songlist_index/ /project/songlist_index/
RUN python /project/songlist_index/setup.py install

COPY songlist_index/ /project/songlist_upload/
RUN python /project/songlist_upload/setup.py install

COPY songlist_index/ /project/song_poller/
RUN python /project/song_poller/setup.py install

RUN rm -fdr /project/*

COPY entrypoint.sh /usr/local/bin/entrypoint
RUN chmod +x /usr/local/bin/entrypoint
ENTRYPOINT ["entrypoint"]