# docker build -t jukebox_alexa_python .
# docker run --rm -it -v $HOME/.aws:/root/.aws -v ${PWD}:/project jukebox_alexa_python /bin/bash
# docker run --rm -it -v $HOME/.aws:/root/.aws -v ${PWD}:/project jukebox_alexa_python songlist_upload
# docker run --rm -it -v $HOME/.aws:/root/.aws -v ${PWD}:/project jukebox_alexa_python songlist_index

FROM python:3.6

RUN mkdir /project
WORKDIR /project

RUN pip install awscli

#
##############################
# songlist_index
##############################
#
COPY songlist_index/requirements.txt /project/songlist_index/requirements.txt
RUN pip install -r /project/songlist_index/requirements.txt -U

##
################################
## songlist_upload
################################
##
COPY songlist_upload/requirements.txt /project/songlist_upload/requirements.txt
RUN pip install -r /project/songlist_upload/requirements.txt -U
#
##
################################
## entrypoint
################################
##
COPY entrypoint.sh /usr/local/bin/entrypoint
RUN chmod +x /usr/local/bin/entrypoint
ENTRYPOINT ["entrypoint"]