version: 0.2
phases:

  install:
    commands:
      - GITDIFF_FILES=$(git diff $(git log --pretty=format:%H -n 2) --name-only)
      - if [[ ${GITDIFF_FILES} != *"/JukeboxAlexa/"* ]]; then echo "*** INFO: No changes found for JukeboxAlexa. Nothing to do." && exit 0; fi
      - echo "*** INFO: Changes found for JukeboxAlexa. Running updates"
      - cd JukeboxAlexa

  build:
    commands:
      - echo "*** INFO: doing dotnet stuff"
      - dotnet restore
      - dotnet build

      - echo "*** INFO: running tests for JukeboxAlexa"
      - dotnet test

  post_build:
    commands:
      - echo "*** INFO: deploy package"
      - lash deploy --tier devel --bootstrap --profile smyleepar
