
---
AWSTemplateFormatVersion: 2010-09-09
Description: Alexa Jukebox Application for us-west-2

Mappings:
  Jukebox:
    RequestQueue:
      Name: jukebox_request_queue.fifo
    RaspberryPiUser:
      Name: jukebox_raspberrypi_user
    RaspberryPiPolicy:
      Name: jukebox_raspberrypi_policy

Resources:

  # user
  JukeboxRaspberryPiUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !FindInMap [Jukebox, RaspberryPiUser, Name]

  # user access keys
  JukeboxRaspberryPiUserAccessKey:
    Type: AWS::IAM::AccessKey
    DependsOn: JukeboxRaspberryPiUser
    Properties:
      UserName: !FindInMap [Jukebox, RaspberryPiUser, Name]

  # sqs
  JukeboxRequestQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      QueueName: !FindInMap [Jukebox, RequestQueue, Name]

  #sqs policy
  JukeboxRequestQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Id: jukebox_request_queue.fifo/SQSDefaultPolicy
        Statement:
          -
            Sid: Sid1493541576892
            Effect: Allow
            Principal:
              AWS: !GetAtt JukeboxRaspberryPiUser.Arn
            Action:
              - sqs:SendMessage
              - sqs:ListQueues
            Resource: !GetAtt JukeboxRequestQueue.Arn
      Queues:
        - Ref: JukeboxRequestQueue

  # policy
  JukeboxRaspberryPiPolicy:
    Type: AWS::IAM::Policy
    DependsOn: JukeboxRaspberryPiUser
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - sqs:ListQueues
            Resource:
               - !GetAtt JukeboxRequestQueue.Arn
      PolicyName: !FindInMap [Jukebox, RaspberryPiPolicy, Name]
      Users:
        - !FindInMap [Jukebox, RaspberryPiUser, Name]

Outputs:
  JukeboxRaspberryPiUser:
    Description: The ARN of the RaspberryPi User
    Value:
      Fn::GetAtt:
        - JukeboxRaspberryPiUser
        - Arn
  JukeboxRaspberryPiUserAccessKey:
    Description: The Access Key for the RaspberryPi User
    Value:
      !Ref JukeboxRaspberryPiUserAccessKey
  JukeboxRaspberryPiUserSecretKey:
    Description: The Secret Key for the RaspberryPi User
    Value:
      !GetAtt JukeboxRaspberryPiUserAccessKey.SecretAccessKey
  QueueURL:
    Description: URL of SQS Queue
    Value:
      Ref: JukeboxRequestQueue
  QueueARN:
    Description: ARN of SQS Queue
    Value:
      Fn::GetAtt:
        - JukeboxRequestQueue
        - Arn
  QueueName:
    Description: Name SQS Queue
    Value:
      Fn::GetAtt:
        - JukeboxRequestQueue
        - QueueName