
---
AWSTemplateFormatVersion: 2010-09-09
Description: Alexa Jukebox Application

Parameters:
  RequestQueueArn:
    Type: String
    Description: Arn of the SQS queue created in jukebox cloudformation us-west-2

Mappings:
  Jukebox:
    LambdaAlexaFunction:
      Name: jukebox_alexa_lambda_function
    LambdaAlexaRole:
      Name: jukebox_alexa_lambda_role
    LambdaAlexaPolicy:
      Name: jukebox_alexa_lambda_policy

Resources:

  # role
  JukeboxLambdaAlexaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !FindInMap [Jukebox, LambdaAlexaRole, Name]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Sid: jukeboxlambda
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  # policy
  JukeboxLambdaAlexaPolicy:
    Type: AWS::IAM::Policy
    DependsOn: JukeboxLambdaAlexaRole
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !Ref RequestQueueArn
          -
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
      PolicyName: !FindInMap [Jukebox, LambdaAlexaPolicy, Name]
      Roles:
        - !FindInMap [Jukebox, LambdaAlexaRole, Name]

Outputs:
  JukeboxLambdaAlexaRole:
    Description: The ARN of the Alexa Lambda Role
    Value:
      Fn::GetAtt:
        - JukeboxLambdaAlexaRole
        - Arn
