
---
AWSTemplateFormatVersion: 2010-09-09
Description: Alexa Jukebox Application - S3 Buckets

Parameters:
  S3BucketJukeboxSongsCsv:
    Type: String
    Description: S3 Bucket the Jukebox Songs CSV are uploaded

Resources:
  S3JukeboxSongsCsv:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3BucketJukeboxSongsCsv

      # NOTE (pattyr, 20180201) NotificationConfiguration below must be commented out on first deploy/creation of cloudformation
      # After first deploy, uncomment and re-deploy to update cloudformation
      # https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-destination-s3/
#      NotificationConfiguration:
#        LambdaConfigurations:
#          - Event: "s3:ObjectCreated:*"
#            Function: !ImportValue jukebox-lambda-cacheindexlambdaarn
#            Filter:
#              S3Key:
#                Rules:
#                  - Name: suffix
#                    Value: xml

Outputs:
  S3JukeboxSongsCsv:
    Description: The ARN of the Jukebox Song CSV Bucket
    Value: !GetAtt S3JukeboxSongsCsv.Arn
    Export:
      Name: jukebox-s3-JukeboxSongsCsvArn
