
---
AWSTemplateFormatVersion: 2010-09-09
Description: Alexa Jukebox Application - Main Stack

Parameters:
  S3BucketJukeboxSongsCsv:
    Type: String
    Description: S3 Bucket the Jukebox Songs CSV are uploaded

Mappings:
  Application:
    Jukebox:
      Name: "Jukebox Alexa"

Resources:

  JukeboxIamRoles:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-iam-roles.yaml

  JukeboxDynamoDb:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: JukeboxIamRoles
    Properties:
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-dynamodb.yaml

  JukeboxSqs:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: JukeboxDynamoDb
    Properties:
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-sqs.yaml

  JukeboxLambdaFunctions:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - JukeboxSqs
      - JukeboxIamRoles
    Properties:
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-lambda.yaml

  JukeboxIamPolicies:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - JukeboxLambdaFunctions
      - JukeboxS3
    Properties:
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-iam-policies.yaml

  JukeboxS3:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: JukeboxLambdaFunctions
    Properties:
      Parameters:
        S3BucketJukeboxSongsCsv: !Ref S3BucketJukeboxSongsCsv
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-s3.yaml

  JukeboxS3Permissions:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - JukeboxS3
      - JukeboxLambdaFunctions
    Properties:
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-s3-permissions.yaml

  JukeboxLambdaTriggers:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - JukeboxLambdaFunctions
      - JukeboxIamPolicies
    Properties:
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-lambda-triggers.yaml

Outputs:
  JukeboxIamRoles:
    Value: JukeboxIamRoles.NestedStackOutputName
    Export:
      Name: jukebox-iam-roles
  JukeboxDynamoDb:
    Value: JukeboxDynamoDb.NestedStackOutputName
    Export:
      Name: jukebox-dynamodb
  JukeboxSqs:
    Value: JukeboxSqs.NestedStackOutputName
    Export:
      Name: jukebox-sqs
  JukeboxLambdaFunctions:
    Value: JukeboxLambdaFunctions.NestedStackOutputName
    Export:
      Name: jukebox-lambda-function
  JukeboxIamPolicies:
    Value: JukeboxIamPolicies.NestedStackOutputName
    Export:
      Name: jukebox-iam-policies
  S3BucketJukeboxSongsCsv:
    Value: JukeboxS3Bucket.Name
    Export:
      Name: jukebox-s3-JukeboxSongsCsvName