
---
AWSTemplateFormatVersion: 2010-09-09
Description: Alexa Jukebox Application - DynamoDB Tables

Mappings:
  Jukebox:
    SongTable:
      Name: JukeboxSongs
    SongCacheTable:
      Name: JukeboxSongsCache

Resources:
  JukeboxDynamodb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !FindInMap [Jukebox, SongTable, Name]
      AttributeDefinitions:
        - AttributeName: track_number
          AttributeType: S
        - AttributeName: search_artist
          AttributeType: S
        - AttributeName: search_title
          AttributeType: S
      KeySchema:
        - AttributeName: track_number
          KeyType: HASH
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: search_title-index
          KeySchema:
            - AttributeName: search_title
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: search_title_artist-index
          KeySchema:
            - AttributeName: search_title
              KeyType: HASH
            - AttributeName: search_artist
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  JukeboxCacheDynamodb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !FindInMap [Jukebox, SongCacheTable, Name]
      AttributeDefinitions:
        - AttributeName: word
          AttributeType: S
      KeySchema:
        - AttributeName: word
          KeyType: HASH
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

Outputs:
  JukeboxDynamodb:
    Description: The ARN of the Jukebox Song DB
    Value: !GetAtt JukeboxDynamodb.Arn
    Export:
      Name: jukebox-dynamodb-JukeboxDynamoDbArn
  JukeboxDynamodbStream:
    Description: The Stream ARN of the Jukebox Song DB
    Value: !GetAtt JukeboxDynamodb.StreamArn
    Export:
      Name: jukebox-dynamodb-JukeboxDynamoDbStreamArn
  JukeboxCacheDynamodb:
    Description: The ARN of the Jukebox Song Cache
    Value: !GetAtt JukeboxCacheDynamodb.Arn
    Export:
      Name: jukebox-dynamodb-JukeboxCacheDynamoDbArn
