
---
AWSTemplateFormatVersion: 2010-09-09
Description: Alexa Jukebox Application - Lambda Functions

Mappings:
  Jukebox:
    AlexaLambda:
      Name: jukebox_alexa
    CacheIndexSongsLambda:
      Name: jukebox_cache_index_songs
    SongListUploadLambda:
      Name: jukebox_song_list_upload

Resources:

  ##### Lambda triggered by update songlist file upload
  JukeboxSongListUploadLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: smyleeface-public
        S3Key: JukeboxAlexa/songlist_upload.zip
      FunctionName: !FindInMap [Jukebox, SongListUploadLambda, Name]
      Handler: index.lambda_handler
      Role: !ImportValue jukebox-iam-roles-SongListUploadLambdaRoleArn
      Runtime: python3.6
      Timeout: 30

  ##### Lambda triggered by DynamoDb
  JukeboxCacheIndexLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: smyleeface-public
        S3Key: JukeboxAlexa/songlist_index.zip
      FunctionName: !FindInMap [Jukebox, CacheIndexSongsLambda, Name]
      Handler: index.lambda_handler
      Role: !ImportValue jukebox-iam-roles-SongIndexLambdaRoleArn
      Runtime: python3.6
      Timeout: 30

  ##### Lambda triggered by alexa
  JukeboxAlexaLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/jukeboxAlexa.zip
      FunctionName: !FindInMap [Jukebox, AlexaLambda, Name]
      Handler: JukeboxAlexa::JukeboxAlexa.Function::FunctionHandler
      Role: !ImportValue jukebox-iam-roles-AlexaLambdaRoleArn
      Runtime: python3.6
      Timeout: 60

Outputs:
  JukeboxAlexaLambdaArn:
    Description: The ARN of the Alexa Lambda Function
    Value:
      Fn::GetAtt:
        - JukeboxAlexaLambda
        - Arn
  JukeboxCacheIndexLambdaName:
    Description: The Name of the Cache Index Lambda Function
    Value: !FindInMap [Jukebox, CacheIndexSongsLambda, Name]
    Export:
      Name: jukebox-lambda-cacheindexlambdaname
  JukeboxCacheIndexLambdaArn:
    Description: The ARN of the Cache Index Lambda Function
    Value:
      Fn::GetAtt:
        - JukeboxCacheIndexLambda
        - Arn
    Export:
      Name: jukebox-lambda-cacheindexlambdaarn
  JukeboxSongListUploadLambdaArn:
    Description: The ARN of the Song List Upload Lambda Function
    Value:
      Fn::GetAtt:
        - JukeboxSongListUploadLambda
        - Arn
    Export:
      Name: jukebox-lambda-songlistuploadlambdaarn