
---
AWSTemplateFormatVersion: 2010-09-09
Description: Alexa Jukebox Application - S3 Buckets

Resources:
  S3JukeboxSongsCsv:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !ImportValue: jukebox-s3-JukeboxSongsCsvName
      NotificationConfiguration:
        LambdaConfigurations:
          -
            Event:
              - "s3:ObjectCreated:*"
            Function: !ImportValue jukebox-lambda-songlistuploadarn
            Filter:
              S3Key:
                Rules:
                  -
                    Name: suffix
                    Value: xml

Outputs:
  S3JukeboxSongsCsv:
    Description: The ARN of the Jukebox Song CSV Bucket
    Value: !GetAtt S3JukeboxSongsCsv.Arn
    Export:
      Name: jukebox-s3-JukeboxSongsCsvArn
