
---
AWSTemplateFormatVersion: 2010-09-09
Description: Alexa Jukebox Application - Lambda Functions

Mappings:
  Jukebox:
    AlexaLambda:
      Name: jukebox_alexa
    CacheIndexSongsLambda:
      Name: jukebox_cache_index_songs

Resources:

  ##### Lambda triggered by alexa
  JukeboxAlexaLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/jukeboxAlexa.zip
      FunctionName: !FindInMap [Jukebox, AlexaLambda, Name]
      Handler: JukeboxAlexa::JukeboxAlexa.Function::FunctionHandler
      Role: !ImportValue jukebox-iam-roles-AlexaLambdaRoleArn
      Runtime: python3.6
      Timeout: 60

  ##### Lambda triggered by DynamoDb
  JukeboxCacheIndexLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/songlist_index.zip
      FunctionName: !FindInMap [Jukebox, CacheIndexSongsLambda, Name]
      Handler: lambda_function.lambda_handler
      Role: !ImportValue jukebox-iam-roles-SongIndexLambdaRoleArn
      Runtime: python3.6
      Timeout: 30

  JukeboxCacheIndexLambdaTrigger:
    Type: "AWS::Lambda::EventSourceMapping"
    Properties:
      BatchSize: 5
      Enabled: true
      StartingPosition: LATEST
      EventSourceArn:
        !Join
          - ''
          - - !ImportValue jukebox-dynamodb-JukeboxDynamoDbArn
            - '/stream/*'
      FunctionName:
        Fn::GetAtt:
          - JukeboxAlexaLambda
          - Arn

Outputs:
  JukeboxAlexaLambdaArn:
    Description: The ARN of the Alexa Lambda Function
    Value:
      Fn::GetAtt:
        - JukeboxAlexaLambda
        - Arn
  JukeboxCacheIndexLambdaArn:
    Description: The ARN of the Cache Index Lambda Function
    Value:
      Fn::GetAtt:
        - JukeboxCacheIndexLambda
        - Arn
