version: 0.2
phases:
  install:
    commands:
      - cd songlist_upload
      - pip install -r requirements.txt -t .
  pre_build:
    commands:
        - python setup.py test
  build:
    commands:
        - zip -r songlist_upload.zip .
  post_build:
    commands:
        - aws s3 cp songlist_upload.zip s3://pattylol-lambda-code-us-west-2/jukebox_alexa/cp songlist_upload.zip

#artifacts:
#  files:
#    - 'songlist_upload.zip'
#  base-directory: songlist_upload
#  discard-paths: yes

# docker build -t jukebox-python -f Dockerfile-python .
# docker tag jukebox-python:latest 892750500233.dkr.ecr.us-west-2.amazonaws.com/jukebox-python:latest
# docker push 892750500233.dkr.ecr.us-west-2.amazonaws.com/jukebox-python:latest
# docker run -it --rm --name songlist_upload -v $HOME/.aws:/root/.aws -v $PWD:/project jukebox-python