Version: 0.3

Name: JukeboxAlexa

Description: JukeboxAlexa Project

Variables:
  DynamoDbIndexNameSearchTitleName: indexNameSearchTitle
  DynamoDbIndexNameSearchTitleArtistName: indexNameSearchTitleArtist

Parameters:
    #
    ##########################
    # Index names in env var
    ##########################
    #
  - Name: IndexNameSearchTitle
    Description: Name of the index for searching the title
    Value: "{{DynamoDbIndexNameSearchTitleName}}"
    
  - Name: IndexNameSearchTitleArtist
    Description: Name of the index for searching the title and artist
    Value: "{{DynamoDbIndexNameSearchTitleArtistName}}"

  #
  ##########################
  # S3 CSV Song file upload
  ##########################
  #
  - Name: S3JukeboxSongsCsv
    Resource:
      Type: "AWS::S3::Bucket"
      Allow: ReadWrite

  #
  ##########################
  # DynamoDB Table - Songs
  ##########################
  #
  - Name: DynamoDbSongs
    Description: DynamoDb table for storing songs
    Resource:
      Type: AWS::DynamoDB::Table
      Allow: ReadWrite
      Properties:
        AttributeDefinitions:
          - AttributeName: song_number
            AttributeType: S
          - AttributeName: search_artist
            AttributeType: S
          - AttributeName: search_title
            AttributeType: S
        KeySchema:
          - AttributeName: song_number
            KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: "{{DynamoDbIndexNameSearchTitleName}}"
            KeySchema:
              - AttributeName: search_title
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: "{{DynamoDbIndexNameSearchTitleArtistName}}"
            KeySchema:
              - AttributeName: search_title
                KeyType: HASH
              - AttributeName: search_artist
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
  #
  ############################################
  # DynamoDB Table - TitleWordCache
  ############################################
  #
  - Name: DynamoDbTitleWordCache
    Description: DynamoDb table for storing received messages
    Resource:
      Type: AWS::DynamoDB::Table
      Allow: ReadWrite
      Properties:
        AttributeDefinitions:
          - AttributeName: word
            AttributeType: S
        KeySchema:
          - AttributeName: word
            KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  #
  ######################
  # SQS Queue
  ######################
  #
  - Name: SqsSongQueue
    Resource:
      Type: AWS::SQS::Queue
      Allow: Send
      Properties:
        FifoQueue: true
        ReceiveMessageWaitTimeSeconds: 20
#
#########################
#        FUNCTIONS
#########################
#
Functions:
  #
  #########################
  # Songlist Upload
  #########################
  #
  - Name: SonglistUpload
    Description: Processes the songs in the uploaded file
    Memory: 192
    Timeout: 30
    Sources:
      - S3: S3JukeboxSongsCsv
  #
  #########################
  # Songlist Index
  #########################
  #
  - Name: SonglistIndex
    Description: Processes the songs added/removed from the index
    Memory: 192
    Timeout: 30
    Sources:
      - DynamoDB: DynamoDbSongs
        BatchSize: 1
  #
  #########################
  # Speaker Request Intent
  #########################
  #
  - Name: SpeakerRequest
    Description: Processes speaker request intnet
    Memory: 192
    Timeout: 30
    Sources:
      - Api: POST /jukebox-alexa/speaker-request
  #
  #########################
  # Play Song Title Request Intent
  #########################
  #
  - Name: PlaySongTitleRequest
    Description: Processes play song request intent
    Memory: 192
    Timeout: 30
    Sources:
      - Api: POST /jukebox-alexa/song-title-request
  #
  #########################
  # Play Song Artist Request Intent
  #########################
  #
  - Name: PlaySongTitleArtistRequest
    Description: Processes play song title and artist request intent
    Memory: 192
    Timeout: 30
    Sources:
      - Api: POST /jukebox-alexa/song-title-artist-request
  #
  #########################
  # Play Number Request Intent
  #########################
  #
  - Name: PlaySongNumberRequest
    Description: Processes play song number request intent
    Memory: 192
    Timeout: 30
    Sources:
      - Api: POST /jukebox-alexa/song-number-request
  #
  #########################
  # Skill Request Intent
  ########################
  #
  - Name: SkillProxyRequest
    Description: Processes speaker request intnet
    Memory: 192
    Timeout: 30
    Environment:
      APIENDPOINT: !Join ['', ["https://", !Ref ModuleRestApi, ".execute-api.", !Ref "AWS::Region", ".amazonaws.com/", !Ref ModuleRestApiStage]]
    Sources:
      - Alexa: "*"
