Module: JukeboxAlexa.Backend
Version: 0.4
Description: JukeboxAlexa Backend Functions

Items:
  #
  ##########################
  # Index names in env var
  ##########################
  #
  - Parameter: DynamoDbIndexNameSearchTitleName
    Description: Name of the index for searching the title
    
  - Parameter: DynamoDbIndexNameSearchTitleArtistName
    Description: Name of the index for searching the title and artist

  #
  ##########################
  # S3 CSV Song file upload
  ##########################
  #
  - Resource: S3JukeboxSongsCsv
    Type: "AWS::S3::Bucket"
    Allow: ReadWrite

  #
  ##########################
  # DynamoDB Table - Songs
  ##########################
  #
  - Resource: DynamoDbSongs
    Description: DynamoDb table for storing songs
    Type: AWS::DynamoDB::Table
    Allow: ReadWrite
    Properties:
      AttributeDefinitions:
        - AttributeName: song_number
          AttributeType: S
        - AttributeName: search_artist
          AttributeType: S
        - AttributeName: search_title
          AttributeType: S
      KeySchema:
        - AttributeName: song_number
          KeyType: HASH
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: !Sub "${DynamoDbIndexNameSearchTitleName}"
          KeySchema:
            - AttributeName: search_title
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: !Sub "${DynamoDbIndexNameSearchTitleArtistName}"
          KeySchema:
            - AttributeName: search_title
              KeyType: HASH
            - AttributeName: search_artist
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  #
  ############################################
  # DynamoDB Table - TitleWordCache
  ############################################
  #
  - Resource: DynamoDbTitleWordCache
    Description: DynamoDb table for storing received messages
    Type: AWS::DynamoDB::Table
    Allow: ReadWrite
    Properties:
      AttributeDefinitions:
        - AttributeName: word
          AttributeType: S
      KeySchema:
        - AttributeName: word
          KeyType: HASH
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  #
  ######################
  # SQS Queue
  ######################
  #
  - Resource: SqsSongQueue
    Type: AWS::SQS::Queue
    Allow: Send
    Properties:
      FifoQueue: true
      ReceiveMessageWaitTimeSeconds: 20
  #
  #########################
  #        FUNCTIONS
  #########################
  #
  #
  #########################
  # Songlist Upload
  #########################
  #
  - Function: SonglistUpload
    Description: Processes the songs in the uploaded file
    Memory: 192
    Timeout: 30
    Scope: all
    Sources:
      - S3: S3JukeboxSongsCsv
        Events:
          - "s3:ObjectCreated:*"
  #
  #########################
  # Songlist Index
  #########################
  #
  - Function: SonglistIndex
    Description: Processes the songs added/removed from the index
    Memory: 192
    Timeout: 30
    Scope: all
    Sources:
      - DynamoDB: DynamoDbSongs
        BatchSize: 1
  #
  #########################
  # Speaker Request Intent
  #########################
  #
  - Function: SpeakerRequest
    Description: Processes speaker request intnet
    Memory: 192
    Timeout: 30
    Scope: all
    Sources:
      - Api: POST /jukebox-alexa/speaker-request
  #
  #########################
  # Play Song Title Request Intent
  #########################
  #
  - Function: PlaySongTitleRequest
    Description: Processes play song request intent
    Memory: 192
    Timeout: 30
    Scope: all
    Sources:
      - Api: POST /jukebox-alexa/song-title-request
  #
  #########################
  # Play Song Artist Request Intent
  #########################
  #
  - Function: PlaySongTitleArtistRequest
    Description: Processes play song title and artist request intent
    Memory: 192
    Timeout: 30
    Scope: all
    Sources:
      - Api: POST /jukebox-alexa/song-title-artist-request
  #
  #########################
  # Play Number Request Intent
  #########################
  #
  - Function: PlaySongNumberRequest
    Description: Processes play song number request intent
    Memory: 192
    Timeout: 30
    Scope: all
    Sources:
      - Api: POST:/jukebox-alexa/song-number-request
  #
  #########################
  # Skill Request Intent
  ########################
  #
  - Function: SkillProxyRequest
    Description: Processes speaker request intnet
    Memory: 192
    Timeout: 30
    Environment:
      APIENDPOINT: !Sub ${Module::RestApi::Url}
    Scope: all
    Sources:
      - Alexa: "*"
