# After initial deploy, uncomment `Comment Block #1` in `jukebox-lambda-main.yaml` and re-deploy to add invoke permission to the lambda function
# After second deploy, swap the `TemplateURL` in `Comment Block #2` below and re-deploy to add event trigger to s3 bucket

---
AWSTemplateFormatVersion: 2010-09-09
Description: Alexa Jukebox Application - Main Stack

Parameters:
  S3BucketJukeboxSongsCsv:
    Type: String
    Description: S3 Bucket the Jukebox Songs CSV are uploaded
  JukeboxSkillId:
    Type: String
    Description: Jukebox Skill Id this is installed on

Mappings:
  Application:
    Jukebox:
      Name: "Jukebox Alexa"

Resources:

  JukeboxIamRoles:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-iam-roles.yaml

  JukeboxDynamoDb:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: JukeboxIamRoles
    Properties:
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-dynamodb.yaml

  JukeboxSqs:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: JukeboxDynamoDb
    Properties:
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-sqs.yaml

  JukeboxLambdaFunctions:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - JukeboxSqs
      - JukeboxIamRoles
    Properties:
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-lambda.yaml

  JukeboxIamPolicies:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - JukeboxLambdaFunctions
      - JukeboxS3
    Properties:
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-iam-policies.yaml

  JukeboxS3:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: JukeboxLambdaFunctions
    Properties:
      Parameters:
        S3BucketJukeboxSongsCsv: !Ref S3BucketJukeboxSongsCsv
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      # START Comment Block #2 REGION
      #TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-s3-create.yaml
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-s3-update.yaml
      # START Comment Block #2 REGION

  JukeboxLambdaTriggers:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - JukeboxLambdaFunctions
      - JukeboxIamPolicies
    Properties:
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-lambda-triggers.yaml

  # START Comment Block #1 REGION
  JukeboxLambdaPermissions:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - JukeboxLambdaFunctions
      - JukeboxS3
    Properties:
      Parameters:
        JukeboxSkillId: !Ref JukeboxSkillId
      Tags:
        -
          Key: AppName
          Value: !FindInMap [Application, Jukebox, Name]
      TemplateURL: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/cloudformation/jukebox-lambda-permissions.yaml
  # END Comment Block #1 REGION

Outputs:
  JukeboxIamRoles:
    Value: JukeboxIamRoles.NestedStackOutputName
    Export:
      Name: jukebox-iam-roles
  JukeboxDynamoDb:
    Value: JukeboxDynamoDb.NestedStackOutputName
    Export:
      Name: jukebox-dynamodb
  JukeboxSqs:
    Value: JukeboxSqs.NestedStackOutputName
    Export:
      Name: jukebox-sqs
  JukeboxLambdaFunctions:
    Value: JukeboxLambdaFunctions.NestedStackOutputName
    Export:
      Name: jukebox-lambda-function
  JukeboxIamPolicies:
    Value: JukeboxIamPolicies.NestedStackOutputName
    Export:
      Name: jukebox-iam-policies
  S3BucketJukeboxSongsCsv:
    Value: JukeboxS3Bucket.Name
    Export:
      Name: jukebox-s3-JukeboxSongsCsvName