version: 0.2
phases:
  build:
    commands:
      - echo '[INFO] restore package and publish'
      - cd JukeboxAlexa
      - dotnet restore
      - dotnet publish
      - cd bin/Debug/netcoreapp2.0/publish
      - zip -r jukeboxAlexa.zip .
artifacts:
  files:
    - '**/*'
  base-directory: JukeboxAlexa/bin/Debug/netcoreapp2.0/publish
  discard-paths: yes
  # publishes to: https://s3-us-west-2.amazonaws.com/smyleeface-public/JukeboxAlexa/LambdaJukeboxAlexa/jukeboxAlexa.zip

