Version: 0.2

Name: JukeboxAlexa

Description: JukeboxAlexa Project

Parameters:

  # TODO: missing source dynamodbstream to port songlist_index to this project

  #
  ##########################
  # DynamoDB Table - Index Permissions
  ##########################
  #
  - Name: DynamoDbSongsTitleIndex
    Import: JukeboxAlexa/SearchSongTitleIndex
    Resource:
      Type: AWS::DynamoDB::Table
      Allow: ReadOnly

  - Name: DynamoDbSongsTitleArtistIndex
    Import: JukeboxAlexa/SearchSongTitleArtistIndex
    Resource:
      Type: AWS::DynamoDB::Table
      Allow: ReadOnly

  #
  ##########################
  # DynamoDB Table - Songs
  ##########################
  #
  - Name: DynamoDbSongs
    Description: DynamoDb table for storing songs
    Resource:
      Type: AWS::DynamoDB::Table
      Allow: ReadOnly
      Properties:
        AttributeDefinitions:
          - AttributeName: track_number
            AttributeType: S
          - AttributeName: search_artist
            AttributeType: S
          - AttributeName: search_title
            AttributeType: S
        KeySchema:
          - AttributeName: track_number
            KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: search_title-index
            KeySchema:
              - AttributeName: search_title
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: search_title_artist-index
            KeySchema:
              - AttributeName: search_title
                KeyType: HASH
              - AttributeName: search_artist
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

  #
  ############################################
  # DynamoDB Table - TitleWordCache
  ############################################
  #
  - Name: DynamoDbTitleWordCache
    Description: DynamoDb table for storing received messages
    Resource:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: word
            AttributeType: S
        KeySchema:
          - AttributeName: word
            KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  #
  ######################
  # SQS Queue
  ######################
  #
  - Name: SqsSongQueue
    Resource:
      Type: AWS::SQS::Queue
      Allow: Send
      Properties:
        FifoQueue: true
        ReceiveMessageWaitTimeSeconds: 20

Functions:

  #
  #########################
  # Skill Request Intent
  #########################
  #
  - Name: SkillProxyRequest
    Description: Processes speaker request intnet
    Memory: 192
    Timeout: 30
    Environment:
      API_ENDPOINT: https://958pj335hl.execute-api.us-west-2.amazonaws.com/LATEST
    Sources:
      - Alexa: amzn1.ask.skill.71c43867-471c-4c66-b9c0-b2c577e1b10f

  #
  #########################
  # Speaker Request Intent
  #########################
  #
  - Name: SpeakerRequest
    Description: Processes speaker request intnet
    Memory: 192
    Timeout: 30
    Sources:
      - Api: POST /jukebox-alexa/speaker-request

  #
  #########################
  # Play Song Title Request Intent
  #########################
  #
  - Name: PlaySongTitleRequest
    Description: Processes play song request intent
    Memory: 192
    Timeout: 30
    Environment:
      INDEX_NAME_SEARCH_TITLE: indexNameSearchTitle
    Sources:
      - Api: POST /jukebox-alexa/song-title-reqeust

  #
  #########################
  # Play Song Artist Request Intent
  #########################
  #
  - Name: PlaySongTitleArtistRequest
    Description: Processes play song title and artist request intent
    Memory: 192
    Timeout: 30
    Environment:
      INDEX_NAME_SEARCH_TITLE: indexNameSearchTitle
      INDEX_NAME_SEARCH_TITLE_ARTIST: indexNameSearchTitleArtist
    Sources:
      - Api: POST /jukebox-alexa/song-title-artist-request

  #
  #########################
  # Play Number Request Intent
  #########################
  #
  - Name: PlaySongNumberRequest
    Description: Processes play song number request intent
    Memory: 192
    Timeout: 30
    Environment:
      INDEX_NAME_SEARCH_TITLE: indexNameSearchTitle
      INDEX_NAME_SEARCH_TITLE_ARTIST: indexNameSearchTitleArtist
    Sources:
      - Api: POST /jukebox-alexa/song-number-request
